### ISSUE TITLE
申请翻译第17章

### ISSUE THREAD

**Issue by zeqing-guo** [huangz1990/real-world-haskell-cn#100]
第一次尝试翻译，如有不足请多指教

**Comment by huangz1990** [comment]
@zeqing-guo ，你好！

欢迎你参加这个翻译项目，你的翻译申请已被记录，期待你的译文。

为了让我们能够及实地对你的译文进行 review ，最好每翻译完一节就 PUSH 上来，谢谢！

**Comment by zeqing-guo** [comment]
@huangz1990 你好！

好的，我知道了。

**Comment by huangz1990** [comment]
Hi， @zeqing-guo  ，想请问一下，翻译工作是否仍在进行，还是已经放弃了？

**Comment by huangz1990** [comment]
zeqing-guo，因为长时间没有提交，你的翻译请求已被关闭，如果要继续进行翻译，请重新发起翻译请求，感谢你对本项目的贡献。
