### ISSUE TITLE
申请翻译第25章

### ISSUE THREAD

**Issue by DrsExplorer** [huangz1990/real-world-haskell-cn#117]
没有翻译经验，如有翻译错误，请多多指教。

**Comment by huangz1990** [comment]
@DrsExplorer 你好，你的翻译请求已收到，有任何问题都可以在这个帖子里面进行讨论，期待你的译文！

**Comment by DrsExplorer** [comment]
@huangz1990 
已经翻译完了，除了后面几节的几个单词不知道怎么翻译，于是我在译文中都直接保留了。请问我下一步该怎么做？
要删掉里面的英文吗？或者直接 pr  过来先让您审核一下？
现在我已经推送到我的版本库上了。

**Comment by huangz1990** [comment]
辛苦了，请通过 PR 将您的译文推送上来，我会直接在 PR 里面进行 review 。

**Comment by DrsExplorer** [comment]
@huangz1990 PR 已经发送。好像这个 PR 把曾经发的给替换掉了。

**Comment by DrsExplorer** [comment]
翻译中使用的名词表（求建议）：

- profiling <del>性能分析/性能调试</del> （性能）剖析
- profiling tool <del>分析工具</del>（性能）剖析工具
- large list 超长列表
- cost centre 消耗集中点
- hot spot 热点
- Constant Applicative Forms 常量函数体
- evaluation 执行/计算
- garbage collector 垃圾收集器
- sum  计算总和
- allocation  内存分配
- pragma  编译指示
- top level function 顶级函数
- pair 对组
- tuple wrapper 元组包装器
- weak head normal form 弱首范式
- normal form reduction
- bang patterns
- tuple wrapper
- unboxed data types
- primitive data types
- fusion
- deforestation

**Comment by sighingnow** [comment]
@DrsExplorer 几个建议
+ 建议将 primitive data types 翻译为“原始数据类型”。
+ unboxed 翻译成“受限”似乎不妥，我觉得翻译成“未封装” 是不是更合适一点？对应的 boxed data types 翻译成 ”封装数据类型“。
+ top level function 翻译成”顶层函数“可能更好一点。

**Comment by huangz1990** [comment]
- primitive data types 译为基本数据类型没有问题，原始数据类型是字面的译法，正确，但不是最常见的，不建议。

- evaluation 可以根据上下文，译为“求值”或者“求值计算”、“求值过程”等。

- top level function 译成“顶层函数” +1 

- pair 和 tuple 保持原文，不译。

- 没有找到标准译法或者好译法的话，直接保留原文，并在原文的旁边加上建议的译法，比如： Constant Applicative Forms （中文译法）。

- 别忘了把翻译的词表记录到 https://github.com/huangz1990/real-world-haskell-cn/blob/master/convention.rst 里面

：）
