### ISSUE TITLE
第二章译注中对 the if expression will also have this type 的理解可能有误

### ISSUE THREAD

**Issue by laneast** [huangz1990/real-world-haskell-cn#118]
第二章有这样一个译注：[译注：这里原文还有一句“the if expression will also have this type”，这是错误的，因为条件部分的表达式只要是 Bool 类型就可以了，没有必要和分支的类型相同。]

我同意 cnhaskell.com 该章节后面 librazy 的评论，这个原文的含义应该是“整个 if 表达式也具有相同的类型“，它指的是整个 if 表达式，直到 else 结束，而不是 if 的条件部分。

**Comment by mumuxme** [comment]
我也这样觉得，应该是指 `if` 表达式的求值结果类型和分支的类型相同。

**Comment by DrsExplorer** [comment]
@huangz1990 能请求这章的译者修改一下吗？

**Comment by scarletsky** [comment]
我觉得你们直接发 PR 过来这里就可以了

**Comment by huangz1990** [comment]
已修复，谢谢各位的提醒。
