### ISSUE TITLE
准备认领15章，对翻译的进度有要求么？第四章看了一下好像都翻完了没有剩一节？

### ISSUE THREAD

**Issue by Forec** [huangz1990/real-world-haskell-cn#120]

**Comment by huangz1990** [comment]
对进度没有特别的要求，但是因为之前有好几位朋友都在认领之后没有提交任何内容就放弃了，所以我建议你先试试翻译一节，看看能不能做下来再进行认领。

是的，第 4 章还剩下 1 节，你也可以翻译这一节试试，如果可行的话，再考虑翻译其他章节。

**Comment by Forec** [comment]
好的，我先试一下翻译第四章剩下的一节

**Comment by huangz1990** [comment]
好的，翻译完了提 PR 就可以了。

另外拼写错误也麻烦你在 pr 里面一并进行修正了。

**Comment by Forec** [comment]
好的，已提 PR。最近在赶论文，想翻译15章但可能要等几天。

**Comment by huangz1990** [comment]
好的，到时候开 issue 申请就可以了。
