### ISSUE TITLE
认领15章第一、二节

### ISSUE THREAD

**Issue by Forec** [huangz1990/real-world-haskell-cn#122]
我想先翻译最前面两节：`Golfing practice`、`Generalised lifting`。最近课有点紧，应该这周末以前能提PR。

**Comment by huangz1990** [comment]
好的，期待你的译文！

**Comment by Forec** [comment]
已提交PR，请查看！下面打算继续翻译15章第3节。

**Comment by huangz1990** [comment]
好的，期待你的译文！
