### ISSUE TITLE
😅翻译要迟一些才能提交了

### ISSUE THREAD

**Issue by Forec** [huangz1990/real-world-haskell-cn#134]
hi，huangz1990：
     非常抱歉，12 月一直在忙学校的一个比赛，现在又快到学期末的考试周了，26 章的翻译我会在 1 月底寒假开始时提交 PR 。开这个 ISSUE 向你说明一下，你看到之后请关闭它，谢谢！

**Comment by huangz1990** [comment]
好的，明白了，考试加油！
