### ISSUE TITLE
对 substitute 的翻译

### ISSUE THREAD

**Issue by shuaishuai** [huangz1990/real-world-haskell-cn#14]
第二章：[变量](http://rwh.readthedocs.org/en/latest/chp/2.html#just-what-is-a-variable-anyway)

原文：

> The critical difference between these two notions of a variable is that in Haskell, once we've bound a variable to an expression, **we know that we can always substitute it for that expression**, because it will not change. In an imperative language, this notion of substitutability does not hold.

译文：

> 对变量的这两种不同的处理方式产生了巨大的差别：在 Haskell 程序里，将一个表达式和一个变量绑定之后，**我们总能用相应的表达式来代替这个变量**。但是在声明式语言里面就没有办法做这样的替换，因为变量的值可能无时不刻都处在改变当中。

我觉得应该是总能`用这个变量代替/代表这个表达式`，强调的是二者之间的一一对应，你就是我，我就是你这样一种关系。

**Comment by huangz1990** [comment]
这里将 substitute 翻译为“代替”应该是没有问题的，仔细思考的话，翻译成“替换”可能会更合适一些： http://www.iciba.com/substitute

如果原作者想表示“代表”的意思的话，那么使用 represent 才更合理。

**Comment by shuaishuai** [comment]
我想说的不是这个问题，我再解释一下。

我觉得`替换`有两种：一是表达式太长太复杂，或者其他原因，用一个变量来替换它使得程序更简洁更可读可复用，凡是我们想用某个表达式的地方，都可以替换成变量；二是这个变量被绑定到了这个表达式，凡是我们需要求值的时候就把变量替换成表达式然后进行求值。

我觉得在这个语境中强调的是第一种意思，这句话的顺序应该是`用变量替换表达式`而不是`用表达式替换变量`。

**Comment by huangz1990** [comment]
啊，原来如此，我明白了，的确是这样，你说得有道理。

“把变量替换成表达式”和“把表达式替换成变量”的意思并不是完全相同的，而前者的意思更贴近原文一些。

我打算把句子改为

> 在 Haskell 程序里面，当变量和表达式进行绑定之后，我们总能将变量替换成相应的表达式。

你觉得如何呢？

**Comment by shuaishuai** [comment]
好呀 :+1:

**Comment by huangz1990** [comment]
完成了： https://github.com/huangz1990/real-world-haskell-cn/commit/51e1b4b2e0641340d57141e2564bd2826ea63c18

谢谢你的意见。 :+1: :+1: :+1:
