### ISSUE TITLE
中文版是怎么和原文保持同步的？

### ISSUE THREAD

**Issue by shuaishuai** [huangz1990/real-world-haskell-cn#15]
第三章还没翻的部分和原文章节好像不一致嘛

**Comment by huangz1990** [comment]
第 3 章已经完成的部分还是 2012 年的时候翻译的，现在内容可能已经发生了变化，如果你有兴趣的话，可以试试根据现在的原文进行翻译和修改，并提交到这里，我会帮忙合并的。

**Comment by shuaishuai** [comment]
恩，我试一下

**Comment by huangz1990** [comment]
:+1:  好的，期待你的贡献。
