### ISSUE TITLE
exercise/ch3/exercise5.hs 有个Bug

### ISSUE THREAD

**Issue by sio-funmatsu** [huangz1990/real-world-haskell-cn#151]
There is a bug in list of odd number.

Prelude> isPalindrome [1,2,1]
*** Exception: Prelude.last: empty list

**Comment by SnowOnion** [comment]
这个 Bug 可以被目前唯一 open 的 PR https://github.com/huangz1990/real-world-haskell-cn/pull/150 所修复。黄老师不妨 merge 之。
