### ISSUE TITLE
申请翻译第三章剩余部分

### ISSUE THREAD

**Issue by Wilbeibi** [huangz1990/real-world-haskell-cn#31]
如题。预计两三天内翻好。

**Comment by huangz1990** [comment]
好的，期待你的译文。  

:smile:

**Comment by hbrls** [comment]
@Wilbeibi hi，进展怎样，我最近又空了一点，可以再翻一两个小节这样

**Comment by Wilbeibi** [comment]
@hbrls 那你先得着吧。我改前面译文的时候遇到不少问题。。然后挺多麻烦事的，

**Comment by huangz1990** [comment]
那这个部分暂时就交给 @hbrls 来翻译了， @Wilbeibi 也辛苦了！ :rose:

**Comment by hbrls** [comment]
进行中

**Comment by huangz1990** [comment]
@hbrls :+1:

**Comment by sancao2** [comment]
我有个问题，http://blog.csdn.net/albert_lee/article/details/4129701这个人曾经翻译过，为什么@huangz1990还要再翻译一次？

**Comment by huangz1990** [comment]
@sancao2 直接看别人翻译的文章，和自己翻译一遍，是完全不同的体验。

对我来说，翻译就是一种学习方法，所以有些时候即使已经有了中文版，我也会去进行翻译。
