### ISSUE TITLE
正在翻译第14章。

### ISSUE THREAD

**Issue by labyrlnth** [huangz1990/real-world-haskell-cn#33]

**Comment by huangz1990** [comment]
好的，期待 labyrlnth 你的第 10 章和第 14 章翻译。 :smile:

**Comment by tiann** [comment]
翻译工作是否正在进行？缺失Monad就少了很大一部分了。

我看
@labyrlnth 认领之后，基本没有上过github了；

**Comment by tiann** [comment]
@labyrlnth 如果你现在没有时间，可否割爱？

**Comment by labyrlnth** [comment]
麻烦把这一章交给别人吧。感谢提醒！

**Comment by labyrlnth** [comment]
@tiann

**Comment by huangz1990** [comment]
那么这一章就交给 @tiann 来翻译吧，请 @tiann 另开一个 issue ，申请第 14 章的翻译权。

这里也感谢 @labyrlnth 为本项目所做的贡献，辛苦了！ :bouquet:

**Comment by tiann** [comment]
@huangz1990 新issue #94 

@labyrlnth 多谢！
