### ISSUE TITLE
18章翻译中

### ISSUE THREAD

**Issue by Javran** [huangz1990/real-world-haskell-cn#36]
如题,同时想就几个翻译约定中未提及的名词讨论一下:

(右手边是我暂时的翻译习惯)

* monad transformer: monad变换器?
* monad transformer stack: monad堆叠?(主要不想和数据结构中的"栈"概念扯上关系)
* underlying monad: 下层monad or 基底monad?
* derive/deriving: 派生?
* typeclass: 类型类?
* lift: 抬举?

**Comment by huangz1990** [comment]
Haskell 译文现在基本上没有什么标准的词语，你可以使用你觉得合适的译法，只要保持全文译法一致，并在《翻译约定》里面记录下你的译法，方便其他译者进行参考就可以了。

就算以后有了更好的译法，也只是一个替换操作的事情，所以不必考虑太多，尽管按照你自己的方法来翻译吧。

你提到的译法我觉得基本都可行，唯一要考虑的是“monad transformer stack”：

1. 既然你把“monad transformer”都翻译成“monad变换器”了，那么“monad transformer stack”至少应该翻译为“monad变换器堆叠”才对。

2. 我个人还是推荐将“monad transformer stack”翻译为“monad变换器栈”，毕竟“stack == 栈”这个概念对于大多数读者来说都是成立的，翻译成“堆叠”可能反而会让人看不出“stack”的意思。此外，“stack”并不一定就指数据结构的“stack”，在一些情况下，“stack”也可以表示多种同类东西的组合，比如很多英文书就使用“server stack”去代表构成服务器的各个软件和服务，而“monad transformer stack”的情况也是类似的。

以上是我的个人意见，希望能给你带来帮助。最后，期待你的译文。

**Comment by Javran** [comment]
感谢回复xD
仔细想想的话你说的确实有道理.还是按栈来说会好一些的样子,我会参考的~

**Comment by huangz1990** [comment]
：）
