### ISSUE TITLE
申请翻译第15章

### ISSUE THREAD

**Issue by zjhmale** [huangz1990/real-world-haskell-cn#41]

**Comment by huangz1990** [comment]
好的，期待你的译文。

另外是翻译第 15 章还是第 16 章，又或者两章一起翻译，最好能够尽快定下来，这样更方便大家协作，谢谢。

**Comment by huangz1990** [comment]
@zjhmale 你好，请问目前确定下来要翻译哪一章了吗？

因为有其他译者想要翻译第 16 章，所以想要知道你是否仍然打算翻译第 16 章，又或者第 16 章的翻译是否已经开始进行了，谢谢。

**Comment by zjhmale** [comment]
我在开始翻译第15章了 不好意思忘记通知你了

**Comment by zjhmale** [comment]
我就确定翻译第15章好了 第16章暂时可能没有精力

**Comment by huangz1990** [comment]
好的，没关系，那我就让另一个译者翻译第 16 章了，感谢你的及时回复，期待你的第 15 章译文！

**Comment by xingxing** [comment]
@zjhmale 我也想试着翻译15章，不知道能否割爱？

**Comment by zjhmale** [comment]
@xingxing  可以的 我这段时间实在太忙了＝ ＝

**Comment by xingxing** [comment]
@zjhmale 好的，多谢。

**Comment by huangz1990** [comment]
那今后第 15 章的翻译就由 @xingxing 负责了，欢迎 @xingxing 加入这个翻译项目，期待你的译文。

:smile:

**Comment by huangz1990** [comment]
Hi， @xingxing ，想请问一下，翻译工作是否仍在进行，还是已经放弃了？

**Comment by xingxing** [comment]
@huangz1990 一直比较忙碌，可以转交其他同学进行。

**Comment by huangz1990** [comment]
@xingxing 好的，那我就重新把 15 章放回待翻译的队列里面吧，辛苦了！
