### ISSUE TITLE
申请翻译第六章剩余部分和第十二章

### ISSUE THREAD

**Issue by YenvY** [huangz1990/real-world-haskell-cn#52]
由于没有细致的看过本书已经翻译完成的内容，想先了解一下除了翻译约定之外还有哪些对译文的约束吗(比如用词风格以及意译的尺度限制等等)？

**Comment by huangz1990** [comment]
Hi，YenvY ，欢迎你参加这个翻译项目。

根据你的情况，我建议你最好在翻译之前，先阅读一些已有的译文，这样可以更直观地了解这个文档的总体风格。

在翻译的过程中，只要在理解原文的基础上，把原文的意思用中文表达出来就可以了，风格不是太大的问题，你可以按照自己的方法来。

不过考虑到目前已有译文的风格都是比较严肃的，所以在翻译的时候请尽量不要使用网络用语。比如不要把“what”翻译为“神马”，不要把“how”翻译为“肿么”，诸如此类。

如果还有其他问题的话我们可以继续讨论，期待你的译文。

**Comment by bishophu** [comment]
我有个问题，第6章现在还有哪些部分没翻译？

建议未完成的翻译，把未完成翻译的小节的原文标题留出来，这样读者在阅读时可以知道进度

**Comment by huangz1990** [comment]
有标示的，未翻译的小节在目录上面都是保持原文的。

比如第 6 章的未翻译小节《JSON typeclasses without overlapping instances》在目录上面就是保持原文的。
