### ISSUE TITLE
申请翻译第16章

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [huangz1990/real-world-haskell-cn#53]
似乎有人申请翻15或16了，所以如果第16章有人在翻的话，就申请第25章 `Profiling and tuning for performance`，如果没人的话，优先申请翻译第16章` The Parsec parsing library`。

**Comment by huangz1990** [comment]
你好，Alaya-in-Matrix ，感谢你参与这个翻译项目。

之前已经有译者表示自己想要翻译第 16 章（https://github.com/huangz1990/real-world-haskell-cn/issues/41），我正在与原来的译者的沟通，看他是否正在翻译 16 章，如果他还没有开始翻译或者不打算翻译第 16 章的话，那么你就可以开始翻译第 16 章了。

请稍等一阵，等原来的翻译者回复了我再联系你。

**Comment by Alaya-in-Matrix** [comment]
好的

发自吕文龙的 iPhone

**Comment by huangz1990** [comment]
@Alaya-in-Matrix 你好。

刚才我问过另一个译者，他说自己没在翻译第 16 章，因此你可以翻译第 16 章，请问你是否要翻译这一章，如果是的话我就进行相应的记录。

**Comment by Alaya-in-Matrix** [comment]
好的，这个有deadline 吗

发自吕文龙的 iPhone

**Comment by huangz1990** [comment]
没有强制的 deadline ，但是译者们一般都会在一两个月之内完成翻译，不过就算翻译时间长些也没关系，你可以按照自己的步调来进行。
