### ISSUE TITLE
申请翻译第19章

### ISSUE THREAD

**Issue by tiancaiamao** [huangz1990/real-world-haskell-cn#54]
之前没接触过haskell，正准备学习这本书。

有一点点scheme(函数式语言)基础，不知道领域知识的局限性会对翻译工作影响有多大。比如像术语的翻译可能会有欠缺，大概要先读一点点你们已经做好的翻译工作再开始。

先试一下翻译这章，预计会在一个月内完成。

**Comment by huangz1990** [comment]
@tiancaiamao 你好，欢迎你加入翻译这个翻译项目，期待你的第 19 章译文。
