### ISSUE TITLE
申请翻译第 25 章

### ISSUE THREAD

**Issue by mitnk** [huangz1990/real-world-haskell-cn#59]
PR https://github.com/huangz1990/real-world-haskell-cn/pull/58

**Comment by huangz1990** [comment]
mitnk，你好！

感谢你参与这个翻译项目，如果有什么问题请在这个页面进行发表，我们可以一起讨论。

期待你的第 25 章译文！

:smile:  :smile:  :smile:

**Comment by huangz1990** [comment]
hi， @mitnk ，想问一下，第 25 章的翻译工作是否仍在继续？进度如何？

**Comment by mitnk** [comment]
@huangz1990 嗯，还在继续，我会提上日程的
一周后再和你更新下进度吧：）

**Comment by huangz1990** [comment]
好的，辛苦了！

最好每完成一节就 push 上来，这样方便我了解你的进度，并且 review 也会容易一些。

**Comment by mitnk** [comment]
see #116
