### ISSUE TITLE
申请翻译第17章

### ISSUE THREAD

**Issue by akakcolin** [huangz1990/real-world-haskell-cn#61]
RT, 预计时间1个月

**Comment by huangz1990** [comment]
@akakcolin 你好，欢迎参加《Real World Haskell》中文翻译项目。

你的翻译申请已被记录，在翻译过程中有任何问题都可以在这个页面发表，我们可以一起讨论。

期待你的第 17 章译文。

**Comment by huangz1990** [comment]
hi， @akakcolin  ，想问一下，第 17 章的翻译工作是否仍在继续？进度如何？

**Comment by akakcolin** [comment]
sorry，没有完成，对自己翻的不是满意就没继续

**Comment by huangz1990** [comment]
好的，那我暂且先把第 17 章重新放到“等待认领”的状态，看看有没有其他译者来接手这一章的翻译，感谢你为本项目所做的努力！  :bouquet:
