### ISSUE TITLE
申请翻译第26章

### ISSUE THREAD

**Issue by xnnyygn** [huangz1990/real-world-haskell-cn#62]
申请翻译第26章。新人，如有不足之处请指摘。

**Comment by huangz1990** [comment]
@xnnyygn 你好，欢迎你加入《Real World Haskell》翻译项目！

你的翻译申请已被记录，如果在翻译过程中有任何问题请在这个页面讨论。

期待你的第 26 章翻译！

:smile:  :smile:  :smile:

**Comment by huangz1990** [comment]
hi， @xnnyygn  ，想问一下，第 26 章的翻译工作是否仍在继续？进度如何？

**Comment by xnnyygn** [comment]
不好意思，前几个月事情比较多，没啥进度。最近打算把之前的东西整理一下，先提交一点，继续翻。

2016年1月4日月曜日、黄健宏<notifications@github.com>さんは書きました:

**Comment by huangz1990** [comment]
好的，明白了，期待你的译文！

**Comment by huangz1990** [comment]
Hi， @xnnyygn  ，想请问一下，翻译工作是否仍在进行，还是已经放弃了？

**Comment by huangz1990** [comment]
xnnyygn，因为长时间没有提交，你的翻译请求已被关闭，如果要继续进行翻译，请重新发起翻译请求，感谢你对本项目的贡献。
