### ISSUE TITLE
申请翻译第四章新增的几个小节

### ISSUE THREAD

**Issue by ruujoa** [huangz1990/real-world-haskell-cn#71]
申请翻译第四章新增的几个小节，Haskell新手，正在阅读《Haskell趣学指南》英文网页版，打算换一个角度去学习Haskell，正好看到这个翻译《真实世界的Haskell》的项目，怀揣着兴奋和忐忑的心情去尝试这个翻译工作，欢迎批评指正，谢谢大家。

**Comment by huangz1990** [comment]
@ruujoa 你好，你的翻译请求已被记录，欢迎你参与本项目的翻译工作。

第 4 章未翻译的几个小节非常适合 Haskell 新手练习，希望这次的翻译能够帮助你更好地理解和认识 Haskell ，期待你的译文！

**Comment by ruujoa** [comment]
请问如何提交自己在本地添加的东西？


我现在在本地创建了一个分支，没敢commit，如下图所示：




请指教，谢谢！


原始邮件
发件人:黄健宏notifications@github.com
收件人:huangz1990/real-world-haskell-cnreal-world-haskell-cn@noreply.github.com
抄送:Yao Luyao3000vlove1999@hotmail.com
发送时间:2015年9月8日(周二) 19:26
主题:Re: [real-world-haskell-cn] 申请翻译第四章新增的几个小结 (#71)


@ruujoa 你好，你的翻译请求已被记录，欢迎你参与本项目的翻译工作。
第 4 章未翻译的几个小节非常适合 Haskell 新手练习，希望这次的翻译能够帮助你更好地理解和认识 Haskell ，期待你的译文！

**Comment by huangz1990** [comment]
提交翻译需要用到 GitHub 的 fork 功能，简单的步骤如下：

1. 点击这个项目右上方的“fork”按钮，GitHub 就会帮你创建一个属于你自己的 RWH 项目。

2. 点击进你自己的 RWH 项目里面，复制项目的地址，然后使用 git clone ，把你的 RWH 项目复制到你的电脑上。

3. 在你的电脑上对 RWH 项目进行修改，完成了之后把它 commit 上 GitHub 上面。

4. 在你对项目进行了修改之后，你的 RWH 项目主页上面就会新出来一行字，问你要不要将你的修改“merge”到原来的项目上面，这时你点击“pull request”按键，按步骤做就可以发送一个 pull request ，之后等待我将你的贡献合并就可以了。

**Comment by huangz1990** [comment]
如果暂时还弄不懂 fork 的操作方法的话，也可以直接把你的翻译内容贴上来，我来帮你提交就可以了。

:smile:

**Comment by ruujoa** [comment]
非常感谢大神的详细解答，我已经安装前一封回信中描述的步骤创建了一个Pull request。请您merge。：P


原始邮件
发件人:黄健宏notifications@github.com
收件人:huangz1990/real-world-haskell-cnreal-world-haskell-cn@noreply.github.com
抄送:Yao Luyao3000vlove1999@hotmail.com
发送时间:2015年9月10日(周四) 17:08
主题:Re: [real-world-haskell-cn] 申请翻译第四章新增的几个小节 (#71)


如果暂时还弄不懂 fork 的操作方法的话，也可以直接把你的翻译内容贴上来，我来帮你提交就可以了。

**Comment by huangz1990** [comment]
已经合并了，辛苦了！

我也对你提交的内容进行了一些格式方面的修正，你可以看看，下次提交贡献的时候就能做得更好一些： https://github.com/huangz1990/real-world-haskell-cn/commit/2cf26e83a2bca3f7bc4beb60d8228e74704274c5

：）

**Comment by ruujoa** [comment]
多谢大神，用Sublime Text编辑的那个RTF文件，可能格式不太对。 嘿嘿


原始邮件
发件人:黄健宏notifications@github.com
收件人:huangz1990/real-world-haskell-cnreal-world-haskell-cn@noreply.github.com
抄送:Yao Luyao3000vlove1999@hotmail.com
发送时间:2015年9月11日(周五) 12:13
主题:Re: [real-world-haskell-cn] 申请翻译第四章新增的几个小节 (#71)


已经合并了，辛苦了！
我也对你提交的内容进行了一些格式方面的修正，你可以看看，下次提交贡献的时候就能做得更好一些： 2cf26e8
：）

**Comment by huangz1990** [comment]
hi， @ruujoa ，请问第 4 章最后几节的翻译工作是否仍在继续？进度如何？

**Comment by ruujoa** [comment]
Hi, 不好意思，最近这个几个月比较忙，目前空下来，我尽快翻译完。

**Comment by huangz1990** [comment]
好的，期待你的译文！

**Comment by huangz1990** [comment]
ruujoa，因为长时间没有提交，你的翻译请求已被关闭，如果要继续进行翻译，请重新发起翻译请求，感谢你对本项目的贡献。
