### ISSUE TITLE
指向附录的链接写成了绝对路径

### ISSUE THREAD

**Issue by hbrls** [huangz1990/real-world-haskell-cn#73]
https://github.com/huangz1990/real-world-haskell-cn/blame/master/chp/1.rst#L46

顺便问下相对路径怎么写？没找到例子

**Comment by huangz1990** [comment]
不太清楚，我也一直只写绝对路径。

**Comment by hbrls** [comment]
现在换域名了，写绝对路径会有问题吧

**Comment by huangz1990** [comment]
搜索了一下，RST 是可以[写相对路径](http://stackoverflow.com/questions/3630386/insert-relative-link-in-restructuredtext)的，但是这个文档目前还没有翻译附录，所以这个问题暂时还不用担心。

：）
