### ISSUE TITLE
示例代码注释

### ISSUE THREAD

**Issue by xingxing** [huangz1990/real-world-haskell-cn#81]
我提议对示例代码中的注视进行翻译，本书中示例代码很多，一些注释对照正文有助于更快理解

**Comment by huangz1990** [comment]
是的，限制有些注释还没有进行翻译，将来会补全的。

**Comment by sancao2** [comment]
有些注释，没有翻译，确实可惜．
比如a class is not a class.像这种废话一样的句子，基本上被漏掉了．然后译者，还以为作者不知道class是Java世界的接口和类型多态的等价物．其实作者想说的事情，不过是他们公用一个单词，下面的文章可能混用class,typeclass这两个词，而已．
