### ISSUE TITLE
优化网站在手机端的显示

### ISSUE THREAD

**Issue by DrsExplorer** [huangz1990/real-world-haskell-cn#82]
能不能优化一下<http://cnhaskell.com/>在手机上的查看？
需要的话我可以帮忙。

**Comment by huangz1990** [comment]
@DrsExplorer ，你好！

目前网站对于移动终端的支持的确不太好，如果你能来帮忙的话那就太好了，不知道你打算进行那些修改？

**Comment by DrsExplorer** [comment]
主要是想修改一下代码块，用chrome在手机上看太小了。header和footer也可以改进一下。

还有，不好意思其实我不是专业做网页设计的，只是有看过这方面的东西，所以不是很在行。
我可以试着做一下，如果效果不理想的话还请更专业的人士帮忙为好。

**Comment by hbrls** [comment]
先放个统计脚本吧，看看有多少移动设备用户，我觉得代码还是在电脑上看比较爽

**Comment by hbrls** [comment]
@huangz1990 现在是自动 build 过去的吗？网站是你自己搞的还是用的 https://readthedocs.org/

**Comment by huangz1990** [comment]
@hbrls 我用脚本在本机 build ，然后 push 上 git pages 。

**Comment by huangz1990** [comment]
@DrsExplorer 如果不是网页设计人员的话，我还是不推荐你去修改这个页面，毕竟现在网站对移动端可能不太友好，但对电脑端还是不错的，如果贸然改动的话，我怕会带来不好的影响。

不过还是谢谢你的美意，我会考虑你的意见的，并在有需要时进行相应的修改。

**Comment by hbrls** [comment]
@DrsExplorer 你觉得手机上哪部分有问题能截个图圈出来吗

**Comment by DrsExplorer** [comment]
@hbrls @huangz1990 我不确定你们知不知道响应式网页设计，就是可以通过修改css使电脑端和手机端呈现不同的效果，所以是对电脑端完全是没影响的。

[自适应网页设计（Responsive Web Design）](http://www.ruanyifeng.com/blog/2012/05/responsive_web_design.html)

**Comment by DrsExplorer** [comment]
![s](https://cloud.githubusercontent.com/assets/3166380/11420946/6848f440-946c-11e5-98a3-5e3127bf95a6.png)


### `<pre>` 块有明显的问题

**Comment by DrsExplorer** [comment]
![screenshot_2015-11-26-18-39-44](https://cloud.githubusercontent.com/assets/3166380/11421055/2709673e-946d-11e5-852d-8d59b0acfe7e.png)

**Comment by DrsExplorer** [comment]
我可以仿照learnyouahaskell优化一下手机端的显示

**Comment by hbrls** [comment]
@DrsExplorer responsive 是个坑，在想明白之前千万不要跳

假如只是觉得 pre 有问题，我可以帮忙处理一下

**Comment by DrsExplorer** [comment]
@hbrls   （。。。响应式确实有些麻烦 = =||）
简单修一下pre就可以了。谢谢了~

**Comment by hbrls** [comment]
@huangz1990 刚才看了一下，`haiku` 大概不是为移动端设计的，假如要支持移动端的话改动较大，也许换个直接支持移动端的模板更合适

**Comment by huangz1990** [comment]
嗯，了解，因为改动较大，所以这个问题就暂时搁置吧。

等项目的所有章节都翻译完毕之后，到时候我再换一个新的样式吧，目前的主要精力还是放在翻译和修正内容上面比较好。

谢谢 @hbrls 的帮助，也感谢 @DrsExplorer 的意见反馈。
