### ISSUE TITLE
申请翻译 27 章

### ISSUE THREAD

**Issue by lkk2003rty** [huangz1990/real-world-haskell-cn#88]
申请翻译第 27 章。新人，如有不足之处请指摘。

**Comment by huangz1990** [comment]
@lkk2003rty 你好，本项目的第 27 章已经翻译完成了： http://cnhaskell.com/chp/27.html

也许你可以考虑通过其他方式来贡献本项目？比如寻找和修正 bug ？

又或者你可以去看看[翻译进度](https://github.com/huangz1990/real-world-haskell-cn#翻译进度与译者名单)里面那些处于“正在进行”的章节，问问这些章节的译者是否仍在进行翻译，如果没有在翻译的话，可以考虑让他们把翻译权让给你。

**Comment by lkk2003rty** [comment]
OK, 谢谢回复

**Comment by huangz1990** [comment]
不客气 ：）
