### ISSUE TITLE
第一章对 interpreter 的翻译不统一

### ISSUE THREAD

**Issue by liancheng** [huangz1990/real-world-haskell-cn#90]
[第一小节][1]将Hugs和`ghci`称为“解析器”，而[第二小节][2]标题又将`ghci`称为“解释器”。实际上二者对应的都是interpreter，“解释器”更符合简体中文习惯。

[1]: http://cnhaskell.com/chp/1.html#haskell
[2]: http://cnhaskell.com/chp/1.html#ghci

**Comment by hepin1989** [comment]
@liancheng @huangz1990 看来需要一个专门的页面,把一些约定的术语写在里面,后面的翻译的时候也有个参照.

**Comment by liancheng** [comment]
查了一下后续章节，第10章中的parser也译作“解析器”，也与第一章冲突了。

**Comment by liancheng** [comment]
@hepin1989 除了术语表之外，还可以用reST的substitution功能，例如：

```rst
Parser是\ |parser|\ ，interpreter是\ |interpreter|\ 。

.. |parser| replace:: 解析器
.. |interpreter| replace:: 解释器
```

编译后效果：

```
Parser是解析器，interpreter是解释器。
```

通过这种方式第一可以统一术语翻译，第二可以轻松替换术语的译法。

**Comment by hepin1989** [comment]
里面没有使用
`Parser(解析器)，interpreter(解释器)`这样的么?这样的翻译方式也行.

substitution + 1

**Comment by sancao2** [comment]
ghci 我看到很多都不翻译的。还有批量替换，我最喜欢了，我重新看一章，马上批量地把每一个句号后面加上换行。便于和英文的句子对应。毕竟都是一句句英中对照的。不知道huangz会不会合并我的版本，不过，我看过之后，我会把多余的换行什么的，合并的.

**Comment by hbrls** [comment]
@sancao2 [progit2-zh](https://github.com/progit/progit2-zh) 用的一种不同的转译工具，所以他们保证英文和中文是一句一换行对应的，然后出来的结果仍然不分段。我们这边好像不行吧？

**Comment by sancao2** [comment]
我简单的替换了一下，然后我先看下去把，大不了合并不了。反正我要让自己看得爽，效率也要高。

**Comment by huangz1990** [comment]
谢谢 @liancheng 以及几位的讨论，项目目前已经有了[翻译约定](http://cnhaskell.com/convention.html)，译者只要按照翻译约定对内容进行翻译就可以了。

目前项目里面的确有一些章节，对于相同的术语使用了不同的处理方法，但这不是一个严重的问题，将来项目翻译完毕之后，只要有一个人总览全文进行修正就可以了。

**Comment by sancao2** [comment]
是的，简单替换，不过一个小时的事情，我就干过。昨天，我发现我的标点和其他作者不统一的，我习惯用英文的半角标点，而不是中文的全角标点，这样不会有乱码比如在代码注释中。但是不统一看起来真别扭。所以我花了一个小时将我的标点都正则匹配出来，然后替换了。。。和代码重构不是一回事情？不管三七二十一，先写出来再说。过早优化是万恶之源，--Knuth。
