### ISSUE TITLE
建议建立一个单独的MD,里面统一约定术语

### ISSUE THREAD

**Issue by hepin1989** [huangz1990/real-world-haskell-cn#91]
refs https://github.com/huangz1990/real-world-haskell-cn/issues/90

通过这样的方式,可以极大的避免术语不一致的情况,同时也需要在README里面提及术语参照文件.

**Comment by fishtreesugar** [comment]
赞, 刚评论完这个[issue](https://github.com/huangz1990/real-world-haskell-cn/pull/87#issuecomment-162809341), 发现同样有人有这个想法!

**Comment by hbrls** [comment]
你们在说这个吗 https://github.com/huangz1990/real-world-haskell-cn/blob/master/convention.rst

**Comment by sancao2** [comment]
很好，对不起之前的傲慢，确实应该统一看一下。。。

**Comment by huangz1990** [comment]
已经在 #90 里面进行了回复，有问题的话可以转到 #90 进行讨论。
