### ISSUE TITLE
申请翻译第14章

### ISSUE THREAD

**Issue by tiann** [huangz1990/real-world-haskell-cn#94]

**Comment by huangz1990** [comment]
@tiann ，欢迎你加入这个项目 ，有任何问题可以随时讨论，期待你的译文！ :bouquet:

**Comment by tiann** [comment]
好的 🌻

**Comment by tiann** [comment]
@huangz1990 翻译的差不多了；我先自己整体看一下，然后需要找个人校对吗？

**Comment by huangz1990** [comment]
你先自己检查下，之后开一个 PR ，我会在 PR 里面再次进行 review 的。
